# Generated by Django 3.0.3 on 2020-02-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('api_key', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('exhausted', models.BooleanField(default=False)),
            ],
        ),
    ]
