# Generated by Django 3.0.3 on 2020-02-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=300)),
                ('published_at', models.DateTimeField()),
                ('video_title', models.CharField(max_length=500)),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('channel_title', models.CharField(max_length=500)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
