# Generated by Django 3.0.3 on 2020-02-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
