# Generated by Django 3.0.3 on 2020-02-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='description',
            field=models.CharField(default='Description unavailable.', max_length=15000),
            preserve_default=False,
        ),
    ]
