# Generated by Django 3.0.3 on 2020-02-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=128)),
                ('publishedAt', models.DateTimeField()),
                ('videoTitle', models.CharField(max_length=500)),
                ('thumbnailUrl', models.CharField(max_length=500)),
                ('channelTitle', models.CharField(max_length=500)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
