# Generated by Django 3.0.3 on 2020-02-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0005_auto_20200211_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='videoId',
            new_name='id',
        ),
    ]
