# Generated by Django 3.0.3 on 2020-02-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_search', '0006_auto_20200211_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='id',
            new_name='videoId',
        ),
    ]
